#!/bin/bash

echo "🎨 Shopvora Logo Setup"
echo "======================"
echo ""
echo "📁 Your logo should be placed in:"
echo "   shopvora-storefront/public/images/logo/logo.png"
echo ""
echo "📋 Logo Requirements:"
echo "   • Format: PNG (recommended) or JPG"
echo "   • Size: 120px × 40px or larger"
echo "   • Background: Transparent (for PNG)"
echo "   • File name: logo.png"
echo ""
echo "🔄 If you don't have a logo yet, the app will show 'Shopvora' text instead."
echo ""
echo "🚀 Your app is running at: http://localhost:8000"
echo ""
echo "📂 Other image folders you can use:"
echo "   • /public/images/categories/ - Category images"
echo "   • /public/images/products/ - Product images"
echo "   • /public/images/banners/ - Hero banner images"
echo "" 